name = "OpenVR"
uuid = "fc4bfce4-4bb3-11e9-3029-21907208b149"
authors = ["Marcus Christian Lehmann <lehmann_ch@web.de>"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
